name: A formal greeting and some random chance
description: "Greet the visitor and generate a random number."

inputs:
  visitor:
    description: "A visitor."
    required: false
    default: "World"
outputs:
  random-number:
    description: "A random number."
    value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Greet the visitor
      id: greet-visitor
      env:
        INPUT_VISITOR: ${{ inputs.visitor }}
      shell: bash
      run: echo "Hello $INPUT_VISITOR."

    - name: Generate a random number
      id: random-number-generator
      shell: bash
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
