name: Jobs Workflow
on: workflow_call
continue-on-error: true

jobs:
  JOB1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat does-not-exist

  JOB2:
    runs-on: ubuntu-latest
    needs: JOB1
    if: ${{ !cancelled() && needs.JOB1.result == 'failure' }}
    steps:
      - run: |
          cat does-not-exist

  JOB3:
    runs-on: ubuntu-latest
    needs: JOB2
    if: ${{ !cancelled() && needs.JOB2.result == 'failure' }}
    steps:
      - run: |
          touch does-exist
