name: Main Workflow
on: [push, workflow_dispatch]

jobs:
  EXAMPLE:
    runs-on: ubuntu-latest
    name: Example Jobs
    steps:
      - id: checkout
        name: Checkout the repository
        uses: actions/checkout@v4µ
        with:
          fetch-depth: 0
      - id: greet
        name: Run the greet composite action
        uses: ./.github/actions/greet
        with:
          visitor: "The Spanish Inquisition"
      - id: commit
        run: |
          git config --local user.name actions[bot]
          git config --local user.email "actions@github.com"
          git checkout random
          echo "${{ steps.greet.outputs.random-number }}" >> random.txt

          git add random.txt
          git commit -m "RANDOM COMMIT"
          git push origin random

      - id: show
        name: Show random number
        env:
          RANDOM_NUMBER: ${{ steps.greet.outputs.random-number }}
        shell: bash
        run: echo random-number "$RANDOM_NUMBER"
      - id: echo
        run: echo "instance-name-echoed=ubuntu-22.04" >> $GITHUB_OUTPUT
    outputs:
      instance-name: ${{ steps.echo.outputs.instance-name-echoed }}

  ATTEMPT:
    needs: EXAMPLE
    runs-on: ${{ needs.EXAMPLE.outputs.instance-name }}
    steps:
      - id: verify
        run: lsb_release -a

  JOBS:
    uses: ./.github/workflows/jobs.yaml

  FINAL:
    runs-on: ubuntu-latest
    needs:
      JOBS
    steps:
      - run: |
          touch does-exist
