name: Main Workflow
on: push

jobs:
  example:
    runs-on: ubuntu-latest
    name: Example Job
    steps:
      - id: checkout
        name: Checkout the repository
        uses: actions/checkout@v4
      - id: greet
        name: Run the greet composite action
        uses: ./.github/actions/greet
        with:
          visitor: "The Spanish Inquisition"
      - id: show
        name: Show random number
        env:
          RANDOM_NUMBER: ${{ steps.greet.outputs.random-number }}
        shell: bash
        run: echo random-number "$RANDOM_NUMBER"

  another:
    runs-on: ubuntu-latest
    name: Another Job
    steps:
      - shell: bash -l {0}
        run: |
          false
          echo "false1"
          false
      - shell: bash
        run: |
          false
          echo "false2"