name: Main Workflow
on: push

jobs:
  EXAMPLE:
    runs-on: ubuntu-latest
    name: Example Jobs
    steps:
      - id: checkout
        name: Checkout the repository
        uses: actions/checkout@v4
      - id: greet
        name: Run the greet composite action
        uses: ./.github/actions/greet
        with:
          visitor: "The Spanish Inquisition"
      - id: show
        name: Show random number
        env:
          RANDOM_NUMBER: ${{ steps.greet.outputs.random-number }}
        shell: bash
        run: echo random-number "$RANDOM_NUMBER"
      - id: echo
        run: echo "instance-name-echoed=$(echo ubuntu-20.04)" >> $GITHUB_OUTPUT
    outputs:
      instance-name:
        value: ${{ steps.echo.outputs.instance-name-echoed }}

  ATTEMPT:
    runs-on: ${{ jobs.EXAMPLE.outputs.created }}
    steps:
      - id: verify
        run: lsb_release -a

  JOBS:
    uses: ./.github/workflows/jobs.yaml

  FINAL:
    runs-on: ubuntu-latest
    needs:
      JOBS
    steps:
      - run: |
          touch does-exist
